services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant:stable"
    ports:
      - "8123:8123" # so we can access the web interface - need this to creat a token if nothing else
    volumes:
      - ha_config:/config
      - ./config/ha/configuration.yaml:/config/configuration.yaml

    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  hassette:
    image: ghcr.io/nodejsmith/hassette:latest-py3.13
    container_name: hassette
    restart: unless-stopped
    depends_on:
      homeassistant:
        condition: service_healthy
    ports:
      - "8126:8126" # so we can see the dashboard
    volumes:
      - ./config:/config
      - .:/apps # use current directory for apps
      - data:/data
      - uv_cache:/uv_cache
    environment:
      - HASSETTE__APP_DIR=/apps/src/hassette_examples # but tell hassette where to find them
      - HASSETTE__TOKEN=${HASSETTE__TOKEN}
      - HASSETTE__BASE_URL=http://homeassistant:8123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8126/api/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  uv_cache:
  data:
  ha_config:
